### ISSUE TITLE
The advamtages?

### ISSUE THREAD

**Issue by youngkzy** [TotallyInformation/alternate-node-red-installer#10]
I was checking for a new version since Node-RED was revised.  I noticed even from last time there are certain "advamtages", but I don't know what that means.  spelling? Just giving you a hard time.  But you probably want to correct the typo.

**Comment by TotallyInformation** [comment]
Apologies for the delayed response.

Thanks for pointing that out, nice to leave things in to see if anyone notices! 😁 Well that's my excuse anyway.

I will try to correct it. But, if there is anything you would like to see added/changed in the repo, please do let me know. I've not changed it in quite a while because it does the job OK and probably includes just enough. Node-RED hasn't really progressed as quickly as expected recently, when v4 is finally released, the base node.js version will move to v16 and I'll need to review the settings.js again but other than that, I don't believe anything significant has changed.

But there is always room for improvement where people suggest things.

**Comment by TotallyInformation** [comment]
And the typo is corrected.
