### ISSUE TITLE
Help "npm start -p 1885"  does not work. 

### ISSUE THREAD

**Issue by youngkzy** [TotallyInformation/alternate-node-red-installer#3]
When using Alternate-node-red-installer,  running "npm start" How do I use -p to alter the Node-RED port if I have otherwise installed Node-RED.  I tried using the -p parameter and it did not work.

on NR forum I'm "@hp_apcc"

**Comment by TotallyInformation** [comment]
Hi. If you used my configuration and settings.js file (BTW, Node-RED does change its settings.js from time-to-time so do compare against the default occasionally and look for new settings). Then you can use an environment variable to control the port rather than using a parameter. 

Even better, you will find a file that the systemd script uses to set environment variables when it starts your node-red instance. 

My version of the settings file actually has quite a few more settings that you can control via environment variables that the default.
